estimator: FasterRCNN
backbone: resnet50
num_classes: 91
task: object_detection
train:
  epochs: 26
  batch_size: 4
  accumulation_steps: 8
  log_frequency: 1000
  dataset:
    name: CocoDetection
    args:
      version: 2017
      split: train
val:
  batch_size: 4
  dataset:
    name: CocoDetection
    args:
      version: 2017
      split: val
test:
  batch_size: 4
  dataset:
    name: CocoDetection
    args:
      version: 2017
      split: val
metrics:
  mAP:
    name: AveragePrecisionBBox2D
    args:
      iou_start: .50
      iou_end: .95
      iou_step: .05
      interpolation: NPointInterpolatedAP
  AP_50IOU:
    name: AveragePrecisionBBox2D
    args:
      iou_start: .50
      iou_end: .50
      iou_step: .05
      interpolation: NPointInterpolatedAP
  mAR:
    name: AverageRecallBBox2D
    args:
      iou_start: .50
      iou_end: .95
      iou_step: .05
      max_detections: 100
optimizer:
  name: Adam
  args:
    lr: 2.0e-4
pretrained: False
pretrained_backbone: True
synchronize_metrics: True
